theme: jekyll-theme-minimal
title: "Robert Yabumoto's Homepage"
description: "Bookmark this to keep an eye on project updates"

website_link: "Check this Kaggle.com dataset on Customer Purchasing Behaviors: [Dataset](https://www.kaggle.com/datasets/hanaksoy/customer-purchasing-behaviors?resource=download)"

website_desc: "This Dataset on Customer Purchasing Behaviors could have strong influence on ads that are tailored to the user knowing which products to promote and when depending on what the customer's salary, how old the customer is, and even the amount of purchases made."

book_rec: "Also check this book out that is intended to be used as an introduction into the field of Deep Learning: [Book](https://www.deeplearningbook.org/)"
book_authors: "This book was made by Ian Goodfellow, Yoshua Bengio, and Aaron Courville published through the MIT Press."
book_desc: "Deep learning has, within the last year or two, become a very interesting topic to me, expecially through advances in Generative AI and it's vast implications in the world of tech."
