theme: jekyll-theme-minimal
title: Robert Yabumoto's Homepage
description: Bookmark this to keep an eye on project updates

desription: Check this Kaggle.com dataset on Customer Purchasing Behaviors: https://www.kaggle.com/datasets/hanaksoy/customer-purchasing-behaviors?resource=download

description: This Dataset on Customer Purchasing Behaviors could have strong influence on ads that are tailored to the user knowing which products to promote and when depending on what the customer's salart, how old the customer is, and even the amount of purchases made.

